TestBill: testCalculateBill.o
	g++ -g -o TestBill testCalculateBill.o -lcppunit

testCalculateBill: testCalculateBill.cpp 
	g++ -g -c testCalculateBill.cpp -lcppunit

clean: 
	echo: "clean"
	rm testCalculateBill.o TestBill